### ISSUE TITLE
Unsteady Grasp

### ISSUE THREAD

**Issue by wangjunyi9999** [google-deepmind/mujoco#786]
Hi,

I'm a student and I'm trying to use MuJoCo for picking object with UR5

I'm looking for some help with grasping. When I test the pick task in MuJoCo simulator, it seems good and everything is fine. However, it is unsteady when I try it in my python code. Either the grasp went through the object or the object slipped out when gripper touches it. Interestingly, these cases occur in the same model file.

Here is a model which explains my question:

<details>
  <summary>minimal XML</summary>

```XML
<mujoco model="ur5gripper">
    <compiler angle="radian" inertiafromgeom="auto" meshdir="visual/" texturedir="texture/"/>
    <option timestep="0.0001" iterations="100" integrator='RK4' collision='all' gravity='0 0 -9.81'/>

    <default>
        <site rgba="0.8 0.6 0.7 0.3" type="ellipsoid" group="3"/>
        <geom contype='1' conaffinity='1' condim='4'  margin="1e-3" solref=".01 1" solimp=".99 .99 .01" />
        <joint armature="0.01" damping=".1"/>
        <default class="UR5">
            <joint damping='65'/>
        </default>

         <default class="UR5e">
            <joint damping='45'/>
        </default>

        <default class="GRIPPER">
            <joint damping='5' solimplimit="0.99 0.999 0.01" solreflimit="0.01 1" armature="100"/>
        </default>
    </default>

    <visual>
        <map fogstart="3" fogend="5" znear="0.05"/>
        <quality shadowsize="2048"/>
        <scale framelength="0.1" framewidth="0.005" contactwidth="0.1" contactheight="0.005" forcewidth="0.01"/>
    </visual>

    <asset>
        <!--Meshes-->
        <mesh name="base"           file="base.stl"     />
        <mesh name="shoulder"       file="shoulder.stl" />
        <mesh name="upperarm"       file="upperarm.stl" />
        <mesh name="forearm"        file="forearm.stl"  />
        <mesh name="wrist1"         file="wrist1.stl"   />
        <mesh name="wrist2"         file="wrist2.stl"   />
        <mesh name="wrist3"         file="wrist3.stl"   />
        <mesh name="gripperpalm"    file="palm.STL"     />
        <mesh name="link_0"         file="link_0.STL"   />
        <mesh name="link_1"         file="link_1.STL"   />
        <mesh name="link_2"         file="link_2.STL"   />
        <mesh name="link_3"         file="link_3.STL"   />

        <mesh name="robotiq_85_base_link_coarse" file="robotiq_85_base_link_coarse.STL" />
        <mesh name="inner_knuckle_coarse" file="inner_knuckle_coarse.STL" />
        <mesh name="inner_finger_coarse" file="inner_finger_coarse.STL" />
        <mesh name="outer_knuckle_coarse" file="outer_knuckle_coarse.STL" />
        <mesh name="outer_finger_coarse" file="outer_finger_coarse.STL" />

        <!--Textures rgb1=".2 .3 .4" rgb2=".1 .2 .3"-->
        <texture name="ur5_tex"     type="2d"       builtin="flat" height="32" width="32" rgb1="0.45 0.45 0.45" />
        <texture name="gripper_tex" type="2d"       builtin="flat" height="32" width="32" rgb1="0.45 0.45 0.45" rgb2="0 0 0"/>
        <texture name="bench_tex"   type="2d"       builtin="flat" height="32" width="32" rgb1="0.7 0.7 0.7" />
        <texture name="sky_tex"     type="skybox"   builtin="gradient" width="100" height="100" rgb1="0.3 0.5 0.7" rgb2="0 0 0" />
        <texture name="texgeom"     type="cube"     builtin="flat" mark="cross" width="127" height="1278" rgb1="0.8 0.6 0.4" rgb2="0.8 0.6 0.4" markrgb="1 1 1" random="0.01" />
        <texture name="floor_tex"   type="2d"        builtin="checker" rgb1=".2 .3 .4" rgb2=".1 0.15 0.2" mark="cross" markrgb=".8 .8 .8" width="100" height="100" />
        <texture name="wood"        type="cube"     file="wood2.png"/>
        <texture name="metal"        type="cube"     file="metal2.png"/>
        <!--Materials-->
        <material name="ur5_mat"        texture="ur5_tex"   shininess="0.9" specular="0.75" reflectance="0.3"/>
        <material name="gripper_mat"    texture="gripper_tex"   shininess="0.9" specular="0.75" reflectance="0.4"/>
        <material name='floor_mat'      texture="floor_tex"  shininess="0.8" texrepeat="10 10" specular="0.7"  reflectance="0.5" />
        <material name='geom'           texture="texgeom"   texuniform="true" />
        <material name="bench_mat"      texture="metal"   shininess="0.1" specular="0.5" reflectance="0.2"/>
        <material name="stand_mat"      texture="wood"   rgba=".8 .8 .8 1"/>
        <!material name="tablecube"      texture="wood" rgba=".8 .8 .8 1"/>
    </asset>
    <!--Contacts-->
    <contact>
        <exclude body1="stand" body2="UR5:base_link"/>
        <exclude body1="UR5:base_link" body2="UR5:shoulder_link"/>
        <exclude body1="UR5:shoulder_link" body2="UR5:upper_arm_link"/>
        <exclude body1="UR5:upper_arm_link" body2="UR5:forearm_link"/>
        <exclude body1="UR5:forearm_link" body2="UR5:wrist_1_link"/>
        <exclude body1="UR5:wrist_1_link" body2="UR5:wrist_2_link"/>
        <exclude body1="UR5:wrist_2_link" body2="UR5:wrist_3_link"/>
        <exclude body1="UR5:ee_link" body2="UR5:wrist_3_link"/>
        <exclude body1="UR5:right_inner_finger" body2="UR5:left_inner_finger"/>
        <!exclude body1="table" body2="object"/>
    </contact>

    <worldbody>
        <light directional="true" diffuse=".4 .4 .4" specular="0.1 0.1 0.1" pos="0 0 5.0" dir="0 0 -1" castshadow="false"/>
        <light directional="true" diffuse=".6 .6 .6" specular="0.2 0.2 0.2" pos="0 0 4" dir="0 0 -1"/>
        <geom name='floor' material="floor_mat" pos='0 0 0' size='5 5 0.1'  type='plane' />
        <include file='table.xml'/>
        <!-- THIS IS DIY UR5 DEMO <include file='ur5.xml'/> -->
        <include file='ur5_origin.xml'/>

        <body name='object' pos='0.5 0.1 1.675' quat='1 0 0 0'> <!0.5 0.1 1.675   0.8 0.33 1.67   >
            <joint type="free" damping="0.007" name="free_joint" />
            <geom size=".02 .02 .02" pos="0 0 0" type="box" rgba='0.3 0.9 0.2 1' mass='2' />
            <site name="object" pos="0 0 0" size="0.02 0.02 0.02" rgba="1 0 0 1" type="sphere"/>
        </body>

        <!-- <body name='hole' pos='-0.5 0.3 1.67'>
            <geom size=".02 .02 .02" pos="0 0 0" type="box" rgba='0.9 0.9 0.2 1'/>
        </body> -->

        <body name="hole" pos="0.5 -0.5 1.67">

            <body name="w1" pos="0.0179 0. 0.025">
                <geom name="w1" rgba="0.3 0.5 0.6 1" type="box" group="1" size="0.0071 0.025 0.02" contype="1" conaffinity="1" />
            </body>
            <body name="w2" pos="-0.0179 0. 0.025">
                <geom name="w2" rgba="0.3 0.5 0.6 1" type="box" group="1" size="0.0071 0.025 0.02" contype="1" conaffinity="1" />
            </body>
            <body name="w3" pos="0. -0.0179 0.025">
                <geom name="w3" rgba="0.3 0.5 0.6 1" type="box" group="1" size="0.0108 0.0071 0.02" contype="1" conaffinity="1" />
            </body>
            <body name="w4" pos="0. 0.0179 0.025">
                <geom name="w4" rgba="0.3 0.5 0.6 1" type="box" group="1" size="0.0108 0.0071 0.02" contype="1" conaffinity="1" />

            </body>
        </body>
        
                         
    </worldbody>

    <!-- <equality>
        <joint name="fingers" joint1="UR5:base_to_rik" joint2="UR5:base_to_lik" polycoef="0 1 0 0 0"/>
    </equality> -->

    <actuator>
        <!include file='actuators/position.xml'/>
       
        <motor name='UR5:shoulder_pan_T' ctrllimited="true" ctrlrange="-2 2" joint='UR5:shoulder_pan_joint' gear="101"/> <!--range -150 150--> <!ctrlrange="-2 2">
        <motor name='UR5:shoulder_lift_T' ctrllimited="true" ctrlrange="-2 2" joint='UR5:shoulder_lift_joint' gear="101"/> <!ctrlrange="-2 2">
        <motor name='UR5:forearm_T' ctrllimited="true" ctrlrange="-2 2" joint='UR5:elbow_joint' gear="101" /> <!ctrlrange="-2 2">
        <motor name='UR5:wrist_1_T' ctrllimited="true" ctrlrange="-1 1" joint='UR5:wrist_1_joint' gear="101"/>  <!--range -28 28-->
        <motor name='UR5:wrist_2_T' ctrllimited="true" ctrlrange="-1 1" joint='UR5:wrist_2_joint' gear="101"/>
        <motor name='UR5:wrist_3_T' ctrllimited="true" ctrlrange="-1 1" joint='UR5:wrist_3_joint' gear="101"/>
        <! grippers>
        <motor name='UR5:gripper_motor_l' ctrllimited="true" ctrlrange="-1 1" joint='UR5:base_to_lik' gear="101"/>
        <motor name='UR5:gripper_motor_r' ctrllimited="true" ctrlrange="-1 1" joint='UR5:base_to_rik' gear="101"/>
    </actuator>
</mujoco>
```

</details>
this is my gripper part code:
<details>
  <summary>minimal XML</summary>

```XML
<!--GRIPPER-->
<mujoco>
    <body name="UR5:robotiq_85_base_link" pos="0 0.0823 0" quat="0.707107 -0.707107 0 0"> <!pos="0 0.0823 0" quat="0.5 -0.5 0.5 0.5 ">
        <inertial pos="0.00021987 -2.3546e-10 0.030163"  quat="0.707058 0.00723369 0.00723345 0.707081" mass="0.30915" diaginertia="0.00030737 0.000289758 0.000199102" />
        <geom type="mesh" rgba="0.1 0.1 0.1 1" friction="0.8 0.8 0.8" mesh="robotiq_85_base_link_coarse" />


    <body name="UR5:left_inner_knuckle" pos="0.0127 0 0.0693075">
        <inertial pos="0.0170975 -3.93809e-10 0.0224918"   quat="0.947655 0 -0.319297 0" mass="1.10931" diaginertia="5.59353e-06 3.96549e-06 1.88108e-06" />
        <geom type="mesh" rgba="0.1 0.1 0.1 1" friction="0.8 0.8 0.8" mesh="inner_knuckle_coarse" />
        <joint name="UR5:base_to_lik" class="GRIPPER" pos="0 0 0" axis="0 1 0" limited="true" range="-1 1" />

        <body name="UR5:left_inner_finger" pos="0.0345853 0 0.045497" >
            <inertial pos="0.00602756 0 0.00669926"  quat="0.699065 0.106339 0.106339 0.699065" mass="4" diaginertia="1.70064e-06 1.58577e-06 3.69621e-07" />
            <geom type="mesh" rgba="0.1 0.1 0.1 1" friction="0.8 0.8 0.8" mesh="inner_finger_coarse" />
        </body>
    </body>

    <body name="UR5:right_inner_knuckle" pos="-0.0127 0 0.0693075" quat="0 0 0 1"> <! mass=0.0110931>
        <inertial pos="0.0168606 3.93808e-10 0.02267"  quat="0.949317 0 -0.314322 0" mass="1.10931" diaginertia="5.59353e-06 3.96549e-06 1.88108e-06" />
        <geom type="mesh" rgba="0.1 0.1 0.1 1" friction="0.8 0.8 0.8" mesh="inner_knuckle_coarse" />
        <joint name="UR5:base_to_rik" class="GRIPPER" pos="0 0 0" axis="0 1 0" limited="true" range="-1 1" />

        <body name="UR5:right_inner_finger" pos="0.034106 0 0.0458574">
            <inertial pos="0.00602756 0 0.00669926"  quat="0.699065 0.106339 0.106339 0.699065" mass="4" diaginertia="1.70064e-06 1.58577e-06 3.69621e-07" />
            <geom type="mesh" rgba="0.1 0.1 0.1 1" friction="0.8 0.8 0.8" mesh="inner_finger_coarse" /><!0.00724255>
        </body>
    </body>  
    
    </body>

</mujoco>
```

</details>
Actually, I googled similar issues before, and the solutions are normally like:

1. change the timestep to 1e-4 1e-5
2. add solref=".01 1" solimp=".99 .99 .01" in <default>
3. make the object larger
4. more stable control
5. Emmmm, waiting for your answer now...

Here is a screenshot / video, illustrating my question:
the video shows how the gripper went through the object:
https://user-images.githubusercontent.com/87897172/227270924-8b8cfbd3-9af6-480e-9eb8-96cbb5b2079a.mp4
the video shows another abnormal issue that the object slipped out from the gripper

https://user-images.githubusercontent.com/87897172/227272755-46eed6ab-0441-484d-aa48-eba6cd25af0e.mp4

the picture shows the object can be held in the gripper very stable (I just change the height of target) . And you can find the force can be shown in the image:

![Screenshot from 2023-03-23 16-48-38](https://user-images.githubusercontent.com/87897172/227271682-d33f7af1-1f6c-4285-89a2-95fbe1c2a94f.png)

Hope someone can provide good suggestions, I really really have no idea now, because it seems existing collision between the gripper and target.

Thanks in advance!

**Comment by wangjunyi9999** [comment]
#698 I tried all solutions according to this issue.

**Comment by cidxb** [comment]
I have also encountered this problem, my solutions are:
1. Make sure you adjust the friction coefficient of your grasper.  It can be done through the geom type attributes 
2. Add `<option noslip_iteration="5"> </option>` to your XML file head,  you can try to modify the number, 5 is fine by me.
3. Add `<option><flag multiccd="enable"/> </option>`
You can try it out.
But I am not sure it will 100% help you, because I have also used this UR5 model, and it act strange when I added these options, I think it is linked to how your geom settings.

**Comment by wangjunyi9999** [comment]
Thanks for your answer. @cidxb 
However,  they do not work for me. My friction values are set '.8 .8 .8' and according to @yuvaltassa  suggestions, `noslip_iterations` cannot be set more than 3. (even if I try to set 5, it does not work ...) 
I suppose the reasons why simulation is unstable are either model files set or controlling methods. For the second possible reason, maybe my gripper force is too large, so the object is 'pop out'. But when I decrease its gains and low its grasping velocity, it will go through the object, i.e. almost no collision.

**Comment by kevinzakka** [comment]
Hi @wangjunyi9999, I would suggest you use the Robotiq 2F85 gripper we have in Menagerie [here](https://github.com/deepmind/mujoco_menagerie/tree/main/robotiq_2f85). The collision geoms for the pads are implemented using multiple boxes to generate more contact points. Would be great if you gave it a try to see if it solves your issues.

**Comment by peterdavidfagan** [comment]
Hi @STAY-Melody, 

I am also working on the same item with the Franka arm. Do you want to combine efforts to try to solve this?

**Comment by wangjunyi9999** [comment]
> Hi! @wangjunyi9999 Have you solved it? I met the same error but with `Franka` arm. Would you mind sharing your solution? Thanks!

Hi, bro, sorry for the late reply. Honestly, I did not find a good solution for the issue, so I changed to another simulator named Isaac Gym. That one provides more stable examples so that you do not have to deep more about modeling work. I recommend you have a try. Hope it helps you.

**Comment by peterdavidfagan** [comment]
Thanks @STAY-Melody for the feedback on your iterations towards solving this problem. I'll also share my learnings here shortly and a solution if I get one. In my current implementation it seems that the arm controller is causing issues rather than the gripper, this being said I will be testing the gripper again once I fix my arm controller.

**Comment by yuvaltassa** [comment]
Hi all, we took a look at the Robotiq gripper. Two issues that we discovered and fixed are:

1. Using a high `impratio` requires elliptic friction cones, fixed [here](https://github.com/google-deepmind/mujoco_menagerie/commit/c5d2e83f49a2a1201153a686de0d26cc02b3bd98).
2. The Robotiq has two box geoms per finger which are what is actually colliding. Some of the previously reported issues involved box-box collisions and it turned out that code has some bugs which should be fixed after 7942fe957ea046750f936ac002d49425e31d9dab.

So the Robotiq gripper from the Menagerie should be pretty good now.

@kevinzakka do we actually have the gripper in the OP?

I suspect it needs some work giving it a better collision layer but TBH I don't recognize it.

Closing for now, please reopen if the above is not sufficient.

**Comment by peterdavidfagan** [comment]
> I'll also share my learnings here shortly and a solution if I get one.

So I ported the following [osc controller](https://github.com/kevinzakka/mjctrl/blob/main/opspace.py) to my codebase and I am getting better results (I still need to perform source build for the updates but plan to do this soon). 

[Screencast from 12-13-2023 05:17:29 PM.webm](https://github.com/google-deepmind/mujoco/assets/42982057/9e673514-9491-4096-aed7-10d084e037c9)

This being said despite setting `gap=margin` for geoms it looks like there is a gap between my gripper fingers and geoms (guessing this is due to the gripper model). 

I also have had issues with commanding open/close of the gripper where continuously commanding close command can result in subsequent open commands not being reactive, I'll post what I learn about this tomorrow as I plan to debug. 

Other than this I am working on making the controller as robust as possible, it works well right now for my purposes but I plan to spend more time with it. @STAY-Melody have you tried the updates with your setup?

**Comment by kevinzakka** [comment]
@peterdavidfagan Your gripper physics still looks a bit weird and the collisions seem off. Here's my controller running on my simple XML which combines the Menagerie and Robotiq models together with no modifications:


https://github.com/google-deepmind/mujoco/assets/10518920/83ebd84e-2f45-418a-ac9e-a570a03befd8

**Comment by maheshr24** [comment]
Hey @yuvaltassa 
My gripper is unable to grasp I really tried multiple iterations of friction for grippers, object but still cant figure this out

https://github.com/user-attachments/assets/6b4866a2-1e1c-4fa1-a0b4-e9318f1c51fd

**Comment by maheshr24** [comment]
> Hi,
> 
> I'm a student and I'm trying to use MuJoCo for picking object with UR5
> 
> I'm looking for some help with grasping. When I test the pick task in MuJoCo simulator, it seems good and everything is fine. However, it is unsteady when I try it in my python code. Either the grasp went through the object or the object slipped out when gripper touches it. Interestingly, these cases occur in the same model file.
> 
> Here is a model which explains my question:
> 
> minimal XML
> this is my gripper part code:
> minimal XML
> Actually, I googled similar issues before, and the solutions are normally like:
> 1. change the timestep to 1e-4 1e-5
> 2. add solref=".01 1" solimp=".99 .99 .01" in
> 3. make the object larger
> 4. more stable control
> 5. Emmmm, waiting for your answer now...
> 
> Here is a screenshot / video, illustrating my question: the video shows how the gripper went through the object: https://user-images.githubusercontent.com/87897172/227270924-8b8cfbd3-9af6-480e-9eb8-96cbb5b2079a.mp4 the video shows another abnormal issue that the object slipped out from the gripper
> 
>  abnormal.pick.mp4 
> the picture shows the object can be held in the gripper very stable (I just change the height of target) . And you can find the force can be shown in the image:
> 
> ![Screenshot from 2023-03-23 16-48-38](https://user-images.githubusercontent.com/87897172/227271682-d33f7af1-1f6c-4285-89a2-95fbe1c2a94f.png)
> 
> Hope someone can provide good suggestions, I really really have no idea now, because it seems existing collision between the gripper and target.
> 
> Thanks in advance!

Hey were you able to fix it?

**Comment by yuvaltassa** [comment]
Did you read this?

https://mujoco.readthedocs.io/en/latest/modeling.html#preventing-slip

**Comment by maheshr24** [comment]
> Did you read this?
> 
> https://mujoco.readthedocs.io/en/latest/modeling.html#preventing-slip

Ahm yes, I played with friction values of gripper, object.

**Comment by amirrazmjoo** [comment]
Hi everyone,

I’ve been trying various approaches to get the robot to grasp an object — including tuning parameters like object size, friction coefficient, and those mentioned in the [MuJoCo documentation on preventing slip](https://mujoco.readthedocs.io/en/latest/modeling.html#preventing-slip). Despite these efforts, I still haven’t been able to get it to work.

@kevinzakka, would you mind sharing your code and xml for picking up the object? I’d like to try it on my end and see what I might be missing.

Here’s the behavior I’m getting right now — it looks like the object stays attached to the table, even though it has a free joint.
https://github.com/user-attachments/assets/534ffe99-253a-47bb-808c-4c534f2e5e72
